// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/group/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/group/usecase.go -destination=mocks/application/group/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	group "github.com/qkitzero/user-service/internal/application/group"
	group0 "github.com/qkitzero/user-service/internal/domain/group"
	membership "github.com/qkitzero/user-service/internal/domain/membership"
	user "github.com/qkitzero/user-service/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupUsecase is a mock of GroupUsecase interface.
type MockGroupUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGroupUsecaseMockRecorder
	isgomock struct{}
}

// MockGroupUsecaseMockRecorder is the mock recorder for MockGroupUsecase.
type MockGroupUsecaseMockRecorder struct {
	mock *MockGroupUsecase
}

// NewMockGroupUsecase creates a new mock instance.
func NewMockGroupUsecase(ctrl *gomock.Controller) *MockGroupUsecase {
	mock := &MockGroupUsecase{ctrl: ctrl}
	mock.recorder = &MockGroupUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupUsecase) EXPECT() *MockGroupUsecaseMockRecorder {
	return m.recorder
}

// AddChildGroup mocks base method.
func (m *MockGroupUsecase) AddChildGroup(ctx context.Context, parentID, childID group0.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChildGroup", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChildGroup indicates an expected call of AddChildGroup.
func (mr *MockGroupUsecaseMockRecorder) AddChildGroup(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChildGroup", reflect.TypeOf((*MockGroupUsecase)(nil).AddChildGroup), ctx, parentID, childID)
}

// AddMember mocks base method.
func (m *MockGroupUsecase) AddMember(ctx context.Context, groupID group0.GroupID, targetUserID user.UserID, role membership.Role) (membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, groupID, targetUserID, role)
	ret0, _ := ret[0].(membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupUsecaseMockRecorder) AddMember(ctx, groupID, targetUserID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupUsecase)(nil).AddMember), ctx, groupID, targetUserID, role)
}

// CreateGroup mocks base method.
func (m *MockGroupUsecase) CreateGroup(ctx context.Context, name group0.GroupName) (group0.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, name)
	ret0, _ := ret[0].(group0.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupUsecaseMockRecorder) CreateGroup(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupUsecase)(nil).CreateGroup), ctx, name)
}

// DeleteGroup mocks base method.
func (m *MockGroupUsecase) DeleteGroup(ctx context.Context, groupID group0.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupUsecaseMockRecorder) DeleteGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupUsecase)(nil).DeleteGroup), ctx, groupID)
}

// GetGroup mocks base method.
func (m *MockGroupUsecase) GetGroup(ctx context.Context, groupID group0.GroupID) (group0.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, groupID)
	ret0, _ := ret[0].(group0.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupUsecaseMockRecorder) GetGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupUsecase)(nil).GetGroup), ctx, groupID)
}

// ListChildGroups mocks base method.
func (m *MockGroupUsecase) ListChildGroups(ctx context.Context, groupID group0.GroupID) ([]group0.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildGroups", ctx, groupID)
	ret0, _ := ret[0].([]group0.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildGroups indicates an expected call of ListChildGroups.
func (mr *MockGroupUsecaseMockRecorder) ListChildGroups(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildGroups", reflect.TypeOf((*MockGroupUsecase)(nil).ListChildGroups), ctx, groupID)
}

// ListMembers mocks base method.
func (m *MockGroupUsecase) ListMembers(ctx context.Context, groupID group0.GroupID) ([]membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, groupID)
	ret0, _ := ret[0].([]membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockGroupUsecaseMockRecorder) ListMembers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockGroupUsecase)(nil).ListMembers), ctx, groupID)
}

// ListMyGroups mocks base method.
func (m *MockGroupUsecase) ListMyGroups(ctx context.Context) ([]group.GroupMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyGroups", ctx)
	ret0, _ := ret[0].([]group.GroupMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyGroups indicates an expected call of ListMyGroups.
func (mr *MockGroupUsecaseMockRecorder) ListMyGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyGroups", reflect.TypeOf((*MockGroupUsecase)(nil).ListMyGroups), ctx)
}

// ListParentGroups mocks base method.
func (m *MockGroupUsecase) ListParentGroups(ctx context.Context, groupID group0.GroupID) ([]group0.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParentGroups", ctx, groupID)
	ret0, _ := ret[0].([]group0.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParentGroups indicates an expected call of ListParentGroups.
func (mr *MockGroupUsecaseMockRecorder) ListParentGroups(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParentGroups", reflect.TypeOf((*MockGroupUsecase)(nil).ListParentGroups), ctx, groupID)
}

// RemoveChildGroup mocks base method.
func (m *MockGroupUsecase) RemoveChildGroup(ctx context.Context, parentID, childID group0.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChildGroup", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveChildGroup indicates an expected call of RemoveChildGroup.
func (mr *MockGroupUsecaseMockRecorder) RemoveChildGroup(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChildGroup", reflect.TypeOf((*MockGroupUsecase)(nil).RemoveChildGroup), ctx, parentID, childID)
}

// RemoveMember mocks base method.
func (m *MockGroupUsecase) RemoveMember(ctx context.Context, groupID group0.GroupID, targetUserID user.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, groupID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockGroupUsecaseMockRecorder) RemoveMember(ctx, groupID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockGroupUsecase)(nil).RemoveMember), ctx, groupID, targetUserID)
}

// UpdateGroup mocks base method.
func (m *MockGroupUsecase) UpdateGroup(ctx context.Context, groupID group0.GroupID, name group0.GroupName) (group0.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, groupID, name)
	ret0, _ := ret[0].(group0.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupUsecaseMockRecorder) UpdateGroup(ctx, groupID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupUsecase)(nil).UpdateGroup), ctx, groupID, name)
}

// UpdateMemberRole mocks base method.
func (m *MockGroupUsecase) UpdateMemberRole(ctx context.Context, groupID group0.GroupID, targetUserID user.UserID, role membership.Role) (membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, groupID, targetUserID, role)
	ret0, _ := ret[0].(membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockGroupUsecaseMockRecorder) UpdateMemberRole(ctx, groupID, targetUserID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockGroupUsecase)(nil).UpdateMemberRole), ctx, groupID, targetUserID, role)
}
