steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/user-service/$COMMIT_SHA
      - -f
      - ./build/user/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/user-service/$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest --secret=user-service-env-file > .env
        gcloud run deploy user-service \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/user-service/$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --min-instances=0 \
          --max-instances=1 \
          --memory=128Mi \
          --cpu=1 \
          --concurrency=80 \
          --timeout=30 \
          --allow-unauthenticated \
          --set-env-vars=$$(cat .env | xargs | sed 's/ /,/g')

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/user-service/$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
