// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/membership/membership.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/membership/membership.go -destination=mocks/domain/membership/mock_membership.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	group "github.com/qkitzero/user-service/internal/domain/group"
	membership "github.com/qkitzero/user-service/internal/domain/membership"
	user "github.com/qkitzero/user-service/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockMembership is a mock of Membership interface.
type MockMembership struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipMockRecorder
	isgomock struct{}
}

// MockMembershipMockRecorder is the mock recorder for MockMembership.
type MockMembershipMockRecorder struct {
	mock *MockMembership
}

// NewMockMembership creates a new mock instance.
func NewMockMembership(ctrl *gomock.Controller) *MockMembership {
	mock := &MockMembership{ctrl: ctrl}
	mock.recorder = &MockMembershipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembership) EXPECT() *MockMembershipMockRecorder {
	return m.recorder
}

// ChangeRole mocks base method.
func (m *MockMembership) ChangeRole(role membership.Role) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ChangeRole", role)
}

// ChangeRole indicates an expected call of ChangeRole.
func (mr *MockMembershipMockRecorder) ChangeRole(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeRole", reflect.TypeOf((*MockMembership)(nil).ChangeRole), role)
}

// GroupID mocks base method.
func (m *MockMembership) GroupID() group.GroupID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupID")
	ret0, _ := ret[0].(group.GroupID)
	return ret0
}

// GroupID indicates an expected call of GroupID.
func (mr *MockMembershipMockRecorder) GroupID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupID", reflect.TypeOf((*MockMembership)(nil).GroupID))
}

// ID mocks base method.
func (m *MockMembership) ID() membership.MembershipID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(membership.MembershipID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockMembershipMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockMembership)(nil).ID))
}

// JoinedAt mocks base method.
func (m *MockMembership) JoinedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// JoinedAt indicates an expected call of JoinedAt.
func (mr *MockMembershipMockRecorder) JoinedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinedAt", reflect.TypeOf((*MockMembership)(nil).JoinedAt))
}

// Role mocks base method.
func (m *MockMembership) Role() membership.Role {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Role")
	ret0, _ := ret[0].(membership.Role)
	return ret0
}

// Role indicates an expected call of Role.
func (mr *MockMembershipMockRecorder) Role() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Role", reflect.TypeOf((*MockMembership)(nil).Role))
}

// UserID mocks base method.
func (m *MockMembership) UserID() user.UserID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(user.UserID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockMembershipMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockMembership)(nil).UserID))
}
