// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/membership/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/membership/repository.go -destination=mocks/domain/membership/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	group "github.com/qkitzero/user-service/internal/domain/group"
	membership "github.com/qkitzero/user-service/internal/domain/membership"
	user "github.com/qkitzero/user-service/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRepository is a mock of MembershipRepository interface.
type MockMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockMembershipRepositoryMockRecorder is the mock recorder for MockMembershipRepository.
type MockMembershipRepositoryMockRecorder struct {
	mock *MockMembershipRepository
}

// NewMockMembershipRepository creates a new mock instance.
func NewMockMembershipRepository(ctrl *gomock.Controller) *MockMembershipRepository {
	mock := &MockMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepository) EXPECT() *MockMembershipRepositoryMockRecorder {
	return m.recorder
}

// CountOwners mocks base method.
func (m *MockMembershipRepository) CountOwners(ctx context.Context, groupID group.GroupID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOwners", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOwners indicates an expected call of CountOwners.
func (mr *MockMembershipRepositoryMockRecorder) CountOwners(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOwners", reflect.TypeOf((*MockMembershipRepository)(nil).CountOwners), ctx, groupID)
}

// Create mocks base method.
func (m *MockMembershipRepository) Create(ctx context.Context, arg1 membership.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMembershipRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMembershipRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockMembershipRepository) Delete(ctx context.Context, userID user.UserID, groupID group.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMembershipRepositoryMockRecorder) Delete(ctx, userID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMembershipRepository)(nil).Delete), ctx, userID, groupID)
}

// FindByUserAndGroup mocks base method.
func (m *MockMembershipRepository) FindByUserAndGroup(ctx context.Context, userID user.UserID, groupID group.GroupID) (membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndGroup", ctx, userID, groupID)
	ret0, _ := ret[0].(membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndGroup indicates an expected call of FindByUserAndGroup.
func (mr *MockMembershipRepositoryMockRecorder) FindByUserAndGroup(ctx, userID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndGroup", reflect.TypeOf((*MockMembershipRepository)(nil).FindByUserAndGroup), ctx, userID, groupID)
}

// ListByGroupID mocks base method.
func (m *MockMembershipRepository) ListByGroupID(ctx context.Context, groupID group.GroupID) ([]membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroupID", ctx, groupID)
	ret0, _ := ret[0].([]membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroupID indicates an expected call of ListByGroupID.
func (mr *MockMembershipRepositoryMockRecorder) ListByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroupID", reflect.TypeOf((*MockMembershipRepository)(nil).ListByGroupID), ctx, groupID)
}

// ListByUserID mocks base method.
func (m *MockMembershipRepository) ListByUserID(ctx context.Context, userID user.UserID) ([]membership.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]membership.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockMembershipRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockMembershipRepository)(nil).ListByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockMembershipRepository) Update(ctx context.Context, arg1 membership.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMembershipRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMembershipRepository)(nil).Update), ctx, arg1)
}
