// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/group/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/group/repository.go -destination=mocks/domain/group/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	group "github.com/qkitzero/user-service/internal/domain/group"
	user "github.com/qkitzero/user-service/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// AddChild mocks base method.
func (m *MockGroupRepository) AddChild(ctx context.Context, parentID, childID group.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChild", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChild indicates an expected call of AddChild.
func (mr *MockGroupRepositoryMockRecorder) AddChild(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChild", reflect.TypeOf((*MockGroupRepository)(nil).AddChild), ctx, parentID, childID)
}

// Create mocks base method.
func (m *MockGroupRepository) Create(ctx context.Context, arg1 group.Group, ownerUserID user.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1, ownerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepositoryMockRecorder) Create(ctx, arg1, ownerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepository)(nil).Create), ctx, arg1, ownerUserID)
}

// Delete mocks base method.
func (m *MockGroupRepository) Delete(ctx context.Context, groupID group.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupRepositoryMockRecorder) Delete(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupRepository)(nil).Delete), ctx, groupID)
}

// FindByID mocks base method.
func (m *MockGroupRepository) FindByID(ctx context.Context, groupID group.GroupID) (group.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, groupID)
	ret0, _ := ret[0].(group.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGroupRepositoryMockRecorder) FindByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGroupRepository)(nil).FindByID), ctx, groupID)
}

// FindByIDs mocks base method.
func (m *MockGroupRepository) FindByIDs(ctx context.Context, groupIDs []group.GroupID) ([]group.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, groupIDs)
	ret0, _ := ret[0].([]group.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockGroupRepositoryMockRecorder) FindByIDs(ctx, groupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockGroupRepository)(nil).FindByIDs), ctx, groupIDs)
}

// FindChildren mocks base method.
func (m *MockGroupRepository) FindChildren(ctx context.Context, parentID group.GroupID) ([]group.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChildren", ctx, parentID)
	ret0, _ := ret[0].([]group.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChildren indicates an expected call of FindChildren.
func (mr *MockGroupRepositoryMockRecorder) FindChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChildren", reflect.TypeOf((*MockGroupRepository)(nil).FindChildren), ctx, parentID)
}

// FindParents mocks base method.
func (m *MockGroupRepository) FindParents(ctx context.Context, childID group.GroupID) ([]group.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParents", ctx, childID)
	ret0, _ := ret[0].([]group.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParents indicates an expected call of FindParents.
func (mr *MockGroupRepositoryMockRecorder) FindParents(ctx, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParents", reflect.TypeOf((*MockGroupRepository)(nil).FindParents), ctx, childID)
}

// RemoveChild mocks base method.
func (m *MockGroupRepository) RemoveChild(ctx context.Context, parentID, childID group.GroupID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChild", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveChild indicates an expected call of RemoveChild.
func (mr *MockGroupRepositoryMockRecorder) RemoveChild(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChild", reflect.TypeOf((*MockGroupRepository)(nil).RemoveChild), ctx, parentID, childID)
}

// Update mocks base method.
func (m *MockGroupRepository) Update(ctx context.Context, arg1 group.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepository)(nil).Update), ctx, arg1)
}
